
class BadMethodCall(Exception):
	pass

class ArgumentError(Exception):
	pass